server {
    listen 80;
    server_name localhost;

    location /filestoring/ {
        proxy_pass http://filestoring-service:8081/filestoring/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /fileanalyser/ {
        proxy_pass http://fileanalyser-service:8082/fileanalyser/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}